name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas

    - name: Install pytest
      run: |
        pip install pytest

    - name: Test with Pytest
      run: |
        pytest

    - name: Lint with Pylint
      run: |
        pylint ./utils.py

    - name: Format with Black
      run: |
        black --check .
